# Generated by Django 4.1.1 on 2022-10-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistgenre',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistgenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artistsong',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistsong',
            name='song',
        ),
        migrations.RemoveField(
            model_name='songalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='songalbum',
            name='song',
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='music_music_app.genre'),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='AlbumArtist',
        ),
        migrations.DeleteModel(
            name='ArtistGenre',
        ),
        migrations.DeleteModel(
            name='ArtistSong',
        ),
        migrations.DeleteModel(
            name='SongAlbum',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='music_music_app.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='music_music_app.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='music_music_app.artist'),
        ),
    ]
