# Generated by Django 4.1.1 on 2022-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0003_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.FileField(upload_to='album_images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(upload_to='artist_images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='audio_files'),
        ),
    ]
