# Generated by Django 4.1.1 on 2022-10-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0004_alter_album_images_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.FileField(upload_to='media/album_images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(upload_to='media/artist_images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='media/audio_files'),
        ),
    ]
