# Generated by Django 4.1.1 on 2022-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0005_alter_album_images_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='images',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
