# Generated by Django 4.1.1 on 2022-10-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0006_remove_album_images_album_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='spotify_id',
        ),
    ]
