# Generated by Django 4.1.1 on 2022-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0008_rename_image_album_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FilePathField(max_length=250),
        ),
    ]
