# Generated by Django 4.1.1 on 2022-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0009_alter_song_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='playlist_shortcuts',
            field=models.ManyToManyField(to='music_music_app.playlist'),
        ),
    ]
