# Generated by Django 4.1.1 on 2022-10-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0010_userdata_playlist_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.CharField(max_length=250),
        ),
    ]
