# Generated by Django 4.1.1 on 2022-10-19 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_music_app', '0011_alter_song_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='song',
            new_name='songs',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
