# Generated by Django 4.1.1 on 2022-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0015_remove_userdata_id_alter_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='a',
            field=models.BooleanField(default=False),
        ),
    ]
