# Generated by Django 4.1.1 on 2022-10-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_music_app', '0016_userdata_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='a',
        ),
    ]
